# Generated by Django 3.2.5 on 2021-08-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='temp_var',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='challenge.submissionsnapshot'),
        ),
    ]
